enum IconName {
  linkedin = "linkedin",
  facebook = "facebook",
  gmail = "gmail",
  github = "github",
  warning = "warning",
  home = "home",
  inventory = "inventory",
  shop = "shop",
  logout = "logout",
  add = "add",
  close = "close",
  circle = "circle",
  spinner = "spinner",
  mop = "mop",
  doc = "doc",
  config = "config",
}
export default IconName;
